### ISSUE TITLE
android app

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords-legacy#10]
It's good to mention that there is a android app for this: 

- Google Play: https://play.google.com/store/apps/details?id=com.intirix.cloudpasswordmanager 

- GitHub: https://github.com/intirix/cloudpasswordmanager

**Comment by intirix** [comment]
I will try updating my Android app to support this project.

**Comment by intirix** [comment]
I installed NC12 with the latest master of this repo and the /api/0.1/passwords endpoint is returning a map with the string id as a key, which matches FCTurner's v20 betas.  FCTurner's v19 returns an array.  My app is currently expecting an array.  One of the stated goals of this project was to support the old API.  What should I do?  Should I update my app to support the new API?  Should I put a version check and use the new API if v20 (just v20 or v20 and later)?

**Comment by pafcioooo** [comment]
I would suggest to go for the last possibility (check v20 and later).

**Comment by pafcioooo** [comment]
BTW, I see that original author of owncloud passwords app has removed his github account.

**Comment by intirix** [comment]
I pushed a change to the Play Store that will use the new API for v20 and later
