### ISSUE TITLE
Guide on how to migrate from fcturner

### ISSUE THREAD

**Issue by alnixon** [marius-wieschollek/passwords-legacy#11]
I can see that the original maintainer has closed shop and this repo appears to be the way forward.

What I really need though is a guide for migrating.  I'd hate to lose all of my passwords!

**Comment by marius-wieschollek** [comment]
This fork of the original app is completely compatible and can be used as drop-in-replacement. Also since the original author does no longer maintain the app, i will do so.

**Comment by marius-wieschollek** [comment]
I just checked it, and did not notice any issues with Nextcloud 11. If you pull the latest version of the app, you should be able to use it on Nextcloud 11 and with PHP 5.6 and newer.

However i feel the need to tell you that Nextcloud 11 is not the current stable version of Nextcloud. The current stable release is Nextcloud 12.0.2. (As listed on their website). If you are using Nextcloud from the git repository, you should switch to the master branch and check out the tag "v12.0.2".

**Comment by alnixon** [comment]
OK, so I took the plunge again and can confirm that the app updated successfully for me, thanks.

Regarding the stable version; I can see that you are correct and the Nextcloud website is listing 12.0.2 as stable.  I was using the version checker within the admin pages and that was informing me that 11.0.4 was the latest on the stable channel.  To get 12.0.2 I would have to switch to the beta channel.

Hopefully the maintainer of the firefox extension will support this fork - I've seen the issue in their repo that you have commented on.

**Comment by alnixon** [comment]
Spoke too soon - I don't know how but this completely breaks webdav for version 11.0.4
I'll go ahead and upgrade to 12.0.2 but I think the compatability of the passwords app does need to be reverted to just 12.

Problems with webdav stack trace:

  | Sabre\DAV\Exception\BadRequest: HTTP/1.1 400 Namespace prefix xsi for noNamespaceSchemaLocation on info is not defined  on line 2, column 86[internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method PROPFIND', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 61:  Sabre\DAV\Server->exec()/var/www/nextcloud/remote.php - line 165:  require_once('/var/www/nextcl...'){main}
-- | --

**Comment by marius-wieschollek** [comment]
Can you tell me when this problem occurred? I was unable to reproduce it on my local testing environment with NC 11.

**Comment by alnixon** [comment]
I haven't had chance to upgrade yet.
The current situation is that I have to keep the passwords app disabled.  As soon as I enable it webdav breaks with the above error.

**Comment by marius-wieschollek** [comment]
I have added a [legacy migration guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration). This will help you to migrate from the old app (Fcturners or mine) to the new and rewritten passwords app.
