### ISSUE TITLE
passwords and passwords-legacy, new enhancement requests location

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords-legacy#12]
Where to submit issues and new enhancement requests: in this repo marius-wieschollek/passwords-legacy or a new repo marius-wieschollek/passwords?

**Comment by marius-wieschollek** [comment]
If you request a feature in passwords-legacy, it will be built into the current app and *might* get ported to the new app. If you request a feature in passwords, it will only be built into the new app.

**Comment by marius-wieschollek** [comment]
@poVoq Can you check if the nightly solves the problem for you as well?
