### ISSUE TITLE
Updating installation instructions and publishing on the Nextcloud app store?

### ISSUE THREAD

**Issue by e-alfred** [marius-wieschollek/passwords-legacy#7]
Hello,

I saw that this part of the installation section seems to be outdated (the link does not work and it still talks about Owncloud):

> 
> ownCloud App store
> I refuse to support this. This system demands repackaging of releases and kills the possibility to freely use GitHub master versions. Repackaging of releases is prone to human error and, more importantly, adds invisible system files to a release when doing this on Mac (like .DS_Store) and Windows (like Thumbs.db). This means local user properties and file system info (privacy sensitive possibly) are sent to a server, which should be avoided at all costs. Did you know forensic scientists can use these files against you? You surely don't want them on any server, any cloud, or anywhere on the internet! Dr Sarah Morris and Dr Howard Chivers wrote an article about this. The ownCloud team should really alter the behaviour of ownCloud pulling apps from their app store, instead of letting app developers interfere with a decent, solid and closed GitHub workflow (as I've been telling them for months). This app is all about privacy and security, the ownCloud app store apparently isn't.

Is this still your policy or do you intend to put them on the Nextcloud store at some point in the future?

**Comment by marius-wieschollek** [comment]
I would like to publish the app on the Nextcloud store in the future. However I have not yet talked to the original author about this.
If I do so, it will probably be later this year, when I have more time.

**Comment by e-alfred** [comment]
I did this already some time ago and he does not like it:

https://github.com/fcturner/passwords/issues/302

**Comment by marius-wieschollek** [comment]
Since it seems like @fcturner does no longer work on his app publicly (That is how I understand his recent readme update) I will push this app to the nextcloud store as soon as i have fixed the most important security flaws in it.

**Comment by e-alfred** [comment]
Strange move. He completely disappeared now and removed all repositories including his account.

There is an Android app to that currently does not work with the latest release too:

https://github.com/intirix/cloudpasswordmanager

**Comment by marius-wieschollek** [comment]
Wiki should be enabled: https://github.com/marius-wieschollek/passwords/wiki
Also since he said that anyone can take it, i will publish it on the store as soon as i have fixed the security issues in this app.

**Comment by e-alfred** [comment]
Well, the license is AGPL, so I can't see any problem with working on it and putting it on the store (that only allows AGPL, MPL 2.0 and Apache License 2.0).

**Comment by pierre-alain-b** [comment]
I do not understand why fcturner has deleted everything and just vanished. I can help package Passwords for Nc if necessary. That being said, the issue 4 merits attention too
https://github.com/marius-wieschollek/passwords/issues/4

**Comment by marius-wieschollek** [comment]
Thanks for the offer. After a quick look into the documentation of the Nextcloud App Store it seems that it has an api. Since i am using GitLab as well i am confident that it is possible to automatize the deployment. But if any issues appear, i will come back to this. However there will be no release before i have fixed #4 and #8 .

**Comment by e-alfred** [comment]
Actually, there is Keeweb too, for opening up Keepass databases. So basically there are already two password managers.

Migrating to Passman from Passwords is quite easy, exporting the passwords as *.csv and importing them into Passman works quite well. The only requirement is doing it before an upgrade to the latest Nextcloud release.

That said, I think the UI with "Vaults" is probably not the thing everybody likes. A flat view is quite nice to have and it also allows sharing of passwords without other people having to create a vault too. This is a big advantage of it.

**Comment by marius-wieschollek** [comment]
I have decided to [rewrite](https://github.com/marius-wieschollek/passwords) the app and will push this to the app store in about three months.
