### ISSUE TITLE
XSS injection

### ISSUE THREAD

**Issue by brantje** [marius-wieschollek/passwords-legacy#9]
During research i found the possibility of injecting javascript into the page:
![image](https://user-images.githubusercontent.com/2758767/28996150-521bad14-79fa-11e7-8f3d-bfae22ba26f0.png)
Results in:
![image](https://user-images.githubusercontent.com/2758767/28996152-614f31e8-79fa-11e7-8a2e-4d0d296deff5.png)

Also happens at the categories. 
Didn't check the csv import.

**Comment by marius-wieschollek** [comment]
Thanks for reporting. I will fix this issue as soon as i can.

**Comment by marius-wieschollek** [comment]
@brantje I have pushed a change to the beta branch which should address this issue. However I was unable to replicate the bug in the way you described it. Could you check if the issue still appears on the beta branch?

**Comment by brantje** [comment]
When i've got some time i'll test and report back.

**Comment by marius-wieschollek** [comment]
I pushed the fix to stable and assume it is done.
